// =============================================
// AURA FIT — Catálogo de Productos
// Precios actualizados desde catálogo real
// =============================================

const PRODUCTS = [
  {
    id: 'baggys',
    name: 'Baggys',
    category: 'Leggings',
    price: 8,
    description: 'Pantalón baggy deportivo, cómodo y versátil para entrenamiento o uso casual.',
    image: 'img/mono_baggys.png',
    colors: ['Azul', 'Azul Marino', 'Blanco', 'Negro', 'Rojo', 'Vinotinto'],
    sizes: ['S', 'M', 'L', 'XL', 'U'],
    stock: { 'Azul-M': 2, 'Azul Marino-S': 1, 'Blanco-M': 1, 'Blanco-L': 1, 'Negro-U': 1, 'Negro-S': 1, 'Negro-M': 1, 'Rojo-L': 2, 'Vinotinto-S': 1, 'Vinotinto-XL': 1 },
    featured: true
  },
  {
    id: 'biker-cruzado',
    name: 'Biker Cruzado ULLU',
    category: 'Leggings',
    price: 8,
    description: 'Biker cruzado de diseño escultor con efecto push up y corte en V.',
    image: 'img/bikers_cruzado.png',
    colors: ['Morado', 'Verde', 'Gris', 'Negro'],
    sizes: ['S/M', 'L/XL'],
    stock: { 'Morado-L/XL': 1, 'Verde-L/XL': 1, 'Gris-L/XL': 3, 'Negro-S/M': 1, 'Negro-L/XL': 1 },
    featured: false
  },
  {
    id: 'bikers',
    name: 'Bikers',
    category: 'Leggings',
    price: 7,
    description: 'Biker deportivo con efecto push up. Talla única.',
    image: 'img/biker_unicolor.png',
    colors: ['Amarillo', 'Azul Eléctrico', 'Negro', 'By Color', 'Gris', 'Morado'],
    sizes: ['U'],
    stock: { 'Amarillo-U': 1, 'Azul Eléctrico-U': 1, 'Negro-U': 1, 'By Color-U': 3, 'Gris-U': 1, 'Morado-U': 1 },
    featured: false
  },
  {
    id: 'conjunto-floyd-biker',
    name: 'Conjunto Floyd Biker',
    category: 'Sets',
    price: 20,
    description: 'Set deportivo completo top + biker con efecto push up.',
    image: 'img/conjunto.png',
    colors: ['Gris', 'Marrón'],
    sizes: ['L/XL'],
    stock: { 'Gris-L/XL': 1, 'Marrón-L/XL': 1 },
    featured: true
  },
  {
    id: 'conjunto-floyd-cierre',
    name: 'Conjunto Floyd Cierre',
    category: 'Sets',
    price: 20,
    description: 'Conjunto deportivo con efecto push up. Top + biker de alta compresión.',
    image: 'img/conjunto2.png',
    colors: ['Gris', 'Negro', 'Rosado'],
    sizes: ['S/M', 'L/XL'],
    stock: { 'Gris-L/XL': 1, 'Negro-S/M': 1, 'Rosado-L/XL': 1 },
    featured: true
  },
  {
    id: 'enterizo-corto',
    name: 'Enterizo Corto',
    category: 'Sets',
    price: 20,
    description: 'Enterizo deportivo de una pieza con efecto push up.',
    image: 'img/enterizo.png',
    colors: ['Azul Marino', 'Marrón', 'Negro'],
    sizes: ['S/M', 'M/L'],
    stock: { 'Azul Marino-M/L': 1, 'Marrón-S/M': 1, 'Negro-M/L': 1 },
    featured: false
  },
  {
    id: 'enterizo-cruzado',
    name: 'Enterizo Cruzado',
    category: 'Sets',
    price: 20,
    description: 'Enterizo deportivo con efecto push up. Talla única.',
    image: 'img/enterizo2.png',
    colors: ['Azul Marino', 'Rojo', 'Rosado'],
    sizes: ['S', 'M'],
    stock: { 'Azul Marino-S': 1, 'Rojo-S': 1, 'Rosado-M': 1 },
    featured: false
  },
  {
    id: 'falda-short',
    name: 'Falda Short Kirios',
    category: 'Leggings',
    price: 10,
    description: 'Falda short deportiva de tela gruesa. Perfecta para tenis o pádel.',
    image: 'img/falda_short.png',
    colors: ['Verde'],
    sizes: ['U'],
    stock: { 'Verde-U': 1 },
    featured: false
  },
  {
    id: 'franela-compresion',
    name: 'Top de Compresión',
    category: 'Tops',
    price: 13,
    description: 'Top de compresión de manga larga. Alta elasticidad y soporte muscular.',
    image: 'img/franela_decompresion.png',
    colors: ['Negro', 'Rojo', 'Blanco'],
    sizes: ['U'],
    stock: { 'Negro-U': 2, 'Rojo-U': 1, 'Blanco-U': 1 },
    featured: true
  },
  {
    id: 'franela-terry',
    name: 'Franela Terry',
    category: 'Tops',
    price: 6,
    description: 'Franela deportiva en tela terry, señida al cuerpo.',
    image: 'img/franela_terry.png',
    colors: ['Fucsia', 'Rosado'],
    sizes: ['U'],
    stock: { 'Fucsia-U': 1, 'Rosado-U': 1 },
    featured: false
  },
  {
    id: 'franela-oversize',
    name: 'Franela Oversize',
    category: 'Tops',
    price: 6,
    description: 'Franela deportiva oversize. Talla única.',
    image: 'img/franela_oversize.png',
    colors: ['Blanco'],
    sizes: ['U'],
    stock: { 'Blanco-U': 3 },
    featured: false
  },
  {
    id: 'jacket',
    name: 'Jacket',
    category: 'Tops',
    price: 15,
    description: 'Jacket deportivo de tela delgada, ideal para entrenamiento.',
    image: 'img/jacket1.png',
    colors: ['Negro', 'Rosado Viejo'],
    sizes: ['M', 'L', 'XL'],
    stock: { 'Negro-M': 1, 'Negro-L': 1, 'Negro-XL': 1, 'Rosado Viejo-M': 1 },
    featured: true
  },
  {
    id: 'licra',
    name: 'Licra',
    category: 'Leggings',
    price: 8,
    description: 'Licra deportiva con efecto push up. Talla única.',
    image: 'img/lycra.png',
    colors: ['Azul Eléctrico', 'Beige', 'Blanco', 'By Color', 'Fucsia', 'Gris', 'Marrón'],
    sizes: ['U'],
    stock: { 'Azul Eléctrico-U': 1, 'Beige-U': 1, 'Blanco-U': 1, 'By Color-U': 4, 'Fucsia-U': 1, 'Gris-U': 1, 'Marrón-U': 1 },
    featured: true
  },
  {
    id: 'licra-alo',
    name: 'Licra ALO',
    category: 'Leggings',
    price: 8,
    description: 'Licra línea ALO con efecto push up.',
    image: 'img/lycra2.png',
    colors: ['Gris', 'Rosado'],
    sizes: ['L'],
    stock: { 'Gris-L': 1, 'Rosado-L': 1 },
    featured: false
  },
  {
    id: 'short-performance',
    name: 'Short Performance',
    category: 'Leggings',
    price: 16,
    description: 'Short deportivo con licra interior. Alto rendimiento.',
    image: 'img/shortrunning.png',
    colors: ['Azul Marino', 'Gris', 'Negro'],
    sizes: ['M'],
    stock: { 'Azul Marino-M': 1, 'Gris-M': 1, 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'short-running',
    name: 'Short Running',
    category: 'Leggings',
    price: 16,
    description: 'Short running con licra interior. Ligero y de secado rápido.',
    image: 'img/shortrunning2.png',
    colors: ['Beige', 'Fucsia', 'Verde Agua'],
    sizes: ['S'],
    stock: { 'Beige-S': 1, 'Fucsia-S': 1, 'Verde Agua-S': 1 },
    featured: false
  },
  {
    id: 'short-running-alo',
    name: 'Short Running ALO',
    category: 'Leggings',
    price: 16,
    description: 'Short running línea ALO con licra interior.',
    image: 'img/shortrunning3.png',
    colors: ['Azul Bebé', 'Beige', 'Negro', 'Vinotinto'],
    sizes: ['S', 'L'],
    stock: { 'Azul Bebé-L': 1, 'Beige-L': 1, 'Negro-S': 1, 'Vinotinto-S': 1 },
    featured: false
  },
  {
    id: 'sudadera',
    name: 'Sudadera',
    category: 'Tops',
    price: 6,
    description: 'Sudadera deportiva señida al cuerpo.',
    image: 'img/sudadera.png',
    colors: ['Blanco', 'Azul Marino', 'Gris'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Blanco-S': 1, 'Azul Marino-L': 1, 'Gris-M': 1 },
    featured: false
  },
  {
    id: 'sudadera-malla',
    name: 'Sudadera de Malla',
    category: 'Tops',
    price: 6,
    description: 'Sudadera ligera con tejido de malla y capucha.',
    image: 'img/sudadera_de_malla.png',
    colors: ['Blanco', 'Negro'],
    sizes: ['U'],
    stock: { 'Blanco-U': 1 },
    featured: false
  },
  {
    id: 'top-malla',
    name: 'Top',
    category: 'Tops',
    price: 5,
    description: 'Top deportivo cómodo y versátil. Talla única.',
    image: 'img/franelilla.png',
    colors: ['Blanco', 'Negro'],
    sizes: ['U'],
    stock: { 'Blanco-U': 1, 'Negro-U': 2 },
    featured: false
  },
  {
    id: 'top-sin-mangas',
    name: 'Top Sin Mangas',
    category: 'Tops',
    price: 5,
    description: 'Top sin mangas deportivo. Talla M.',
    image: 'img/franelilla2.png',
    colors: ['Beige', 'Marrón', 'Negro'],
    sizes: ['M'],
    stock: { 'Beige-M': 1, 'Marrón-M': 1, 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'top-sosten',
    name: 'Top con Copa',
    category: 'Tops',
    price: 5,
    description: 'Top sostén deportivo con copa integrada.',
    image: 'img/franelilla3.png',
    colors: ['Borgoña', 'Rojo'],
    sizes: ['S'],
    stock: { 'Borgoña-S': 1, 'Rojo-S': 1 },
    featured: true
  },
  {
    id: 'top-tirantes',
    name: 'Top Tirantes',
    category: 'Tops',
    price: 5,
    description: 'Top de tirantes con push up. Talla única.',
    image: 'img/franelilla4.png',
    colors: ['Blanco'],
    sizes: ['S', 'M'],
    stock: { 'Blanco-S': 1, 'Blanco-M': 1 },
    featured: false
  },
  {
    id: 'mono-deportivo',
    name: 'Mono Deportivo',
    category: 'Sets',
    price: 20,
    description: 'Mono deportivo de una pieza con efecto push up.',
    image: 'img/mono_deportivo.png',
    colors: ['Negro', 'Gris', 'Azul Marino'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Negro-M': 1, 'Gris-M': 1 },
    featured: true
  },
  {
    id: 'colas',
    name: 'Colas Deportivas',
    category: 'Accesorios',
    price: 3,
    description: 'Colas para el cabello, paquete variado.',
    image: 'img/colitas.png',
    colors: ['By Color', 'Negro'],
    sizes: ['U'],
    stock: { 'By Color-U': 20, 'Negro-U': 20 },
    featured: false
  },
  {
    id: 'colas-seda',
    name: 'Colas de Seda',
    category: 'Accesorios',
    price: 5,
    description: 'Colas de seda suaves, no dañan el cabello.',
    image: 'img/colitas_satin.png',
    colors: ['By Color'],
    sizes: ['U'],
    stock: { 'By Color-U': 5 },
    featured: false
  },
  {
    id: 'lentes',
    name: 'Lentes Deportivos',
    category: 'Accesorios',
    price: 10,
    description: 'Lentes deportivos con protección UV.',
    image: 'img/lentes.png',
    colors: ['Negro', 'By Color'],
    sizes: ['U'],
    stock: { 'Negro-U': 2, 'By Color-U': 1 },
    featured: false
  },
  {
    id: 'bolso-running',
    name: 'Bolso Running',
    category: 'Accesorios',
    price: 12,
    description: 'Bolso running ligero para llevar lo esencial.',
    image: 'img/placeholder.png',
    colors: ['Negro'],
    sizes: ['U'],
    stock: { 'Negro-U': 1 },
    featured: false
  },
  {
    id: 'ligas',
    name: 'Juego de Ligas 5 Niveles',
    category: 'Accesorios',
    price: 8,
    description: 'Set de 5 ligas de resistencia progresiva para glúteos y piernas.',
    image: 'img/placeholder.png',
    colors: ['Azul', 'Rosado'],
    sizes: ['U'],
    stock: { 'Azul-U': 1, 'Rosado-U': 1 },
    featured: false
  },
  {
    id: 'medias-alo',
    name: 'Medias ALO',
    category: 'Accesorios',
    price: 6,
    description: 'Medias deportivas línea ALO.',
    image: 'img/placeholder.png',
    colors: ['By Color'],
    sizes: ['U'],
    stock: { 'By Color-U': 12 },
    featured: false
  }
];

if (typeof module !== 'undefined') module.exports = { PRODUCTS };
