const PRODUCTS = [
  // ── LEGGINGS / BOTTOMS DAMA ──────────────────────────────
  {
    id: 'baggys',
    name: 'Mono Baggys',
    category: 'Leggings',
    price: 12,
    description: 'Pantalón baggy deportivo con efecto push up.',
    image: 'img/mono_baggys.png',
    colorImages: {
      'Negro':       'img/mono_baggys.png',
      'Gris':        'img/mono_baggys2.png',
      'Blanco':      'img/mono_baggys3.png',
      'Burdeos':     'img/mono_baggys4.png',
      'Vinotinto':   'img/mono_baggys5.png',
      'Azul Marino': 'img/mono_baggys6.png',
      'Azul':        'img/mono_baggys7.png'
    },
    colors: ['Negro', 'Gris', 'Blanco', 'Burdeos', 'Vinotinto', 'Azul Marino', 'Azul'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: true
  },
  {
    id: 'biker-cruzado',
    name: 'Biker Cruzado',
    category: 'Leggings',
    price: 8,
    description: 'Biker cruzado con efecto push up y corte en V.',
    image: 'img/bikers_cruzado.png',
    colorImages: {
      'Rosado':      'img/bikers_cruzado.png',
      'Negro':       'img/bikers_cruzado3.png',
      'Gris':        'img/bikers_cruzado4.png',
      'Verde Claro': 'img/bikers_cruzado5.png',
      'Rosa':        'img/bikers_cruzado6.png'
    },
    colors: ['Rosado', 'Negro', 'Gris', 'Verde Claro', 'Rosa'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'bikers',
    name: 'Biker Unicolor',
    category: 'Leggings',
    price: 7,
    description: 'Biker deportivo con efecto push up.',
    image: 'img/biker_unicolor.png',
    colorImages: {
      'Lila':   'img/biker_unicolor.png',
      'Gris':   'img/biker_unicolor2.png',
      'Marrón': 'img/biker_unicolor3.png'
    },
    colors: ['Lila', 'Gris', 'Marrón'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'biker-degradado',
    name: 'Biker Degradado',
    category: 'Leggings',
    price: 8,
    description: 'Biker degradado bicolor con efecto push up.',
    image: 'img/biker_degradado.png',
    colorImages: {
      'Azul y Rosa':    'img/biker_degradado.png',
      'Negro y Blanco': 'img/biker_degradado2.png',
      'Rosado y Lila':  'img/biker_degradado3.png',
      'Azul':           'img/biker_degradado4.png'
    },
    colors: ['Azul y Rosa', 'Negro y Blanco', 'Rosado y Lila', 'Azul'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'licra-unicolor',
    name: 'Licra Unicolor',
    category: 'Leggings',
    price: 8,
    description: 'Licra deportiva con efecto push up.',
    image: 'img/lycra.png',
    colorImages: {
      'Gris Oscuro': 'img/lycra.png',
      'Rosado':      'img/lycra2.png',
      'Gris Claro':  'img/lycra3.png',
      'Azul Gris':   'img/lycra4.png',
      'Verde Khaki': 'img/lycra5.png',
      'Marrón':      'img/lycra6.png'
    },
    colors: ['Gris Oscuro', 'Rosado', 'Gris Claro', 'Azul Gris', 'Verde Khaki', 'Marrón'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: true
  },
  {
    id: 'licra-degradada',
    name: 'Licra Degradada',
    category: 'Leggings',
    price: 8,
    description: 'Licra degradada bicolor con efecto push up.',
    image: 'img/lycra7.png',
    colorImages: {
      'Azul Claro': 'img/lycra7.png',
      'Rosado':     'img/lycra9.png',
      'Negro':      'img/lycra10.png'
    },
    colors: ['Azul Claro', 'Rosado', 'Negro'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'falda-short',
    name: 'Falda Short',
    category: 'Leggings',
    price: 10,
    description: 'Falda short deportiva de tela gruesa.',
    image: 'img/falda_short.png',
    colors: ['Verde'],
    sizes: ['U'],
    stock: { 'Verde-U': 1 },
    featured: false
  },
  {
    id: 'short-running',
    name: 'Short Running',
    category: 'Leggings',
    price: 16,
    description: 'Short running con licra interior. Ligero y de secado rápido.',
    image: 'img/shortrunning.png',
    colorImages: {
      'Marrón':        'img/shortrunning.png',
      'Vinotinto':     'img/shortrunning2.png',
      'Azul Claro':    'img/shortrunning3.png',
      'Negro Doble':   'img/shortrunning4.png',
      'Beige Oscuro':  'img/shortrunning5.png',
      'Fucsia':        'img/shortrunning6.png',
      'Beige Claro':   'img/shortrunning7.png',
      'Crema':         'img/shortrunning8.png',
      'Negro Liso':    'img/shortrunning9.png',
      'Negro Sport':   'img/shortrunning10.png',
      'Azul Marino':   'img/shortrunning11.png'
    },
    colors: ['Marrón','Vinotinto','Azul Claro','Negro Doble','Beige Oscuro','Fucsia','Beige Claro','Crema','Negro Liso','Negro Sport','Azul Marino'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: true
  },
  // ── TOPS DAMA ────────────────────────────────────────────
  {
    id: 'top-copa',
    name: 'Top con Copa',
    category: 'Tops',
    price: 5,
    description: 'Top sostén con copa integrada.',
    image: 'img/top4.png',
    colorImages: {
      'Rosado': 'img/top4.png',
      'Blanco':  'img/top5.png'
    },
    colors: ['Rosado', 'Blanco'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'top-deportivo',
    name: 'Top Deportivo',
    category: 'Tops',
    price: 5,
    description: 'Top deportivo cómodo y versátil.',
    image: 'img/top.png',
    colorImages: {
      'Azul':     'img/top.png',
      'Amarillo': 'img/top2.png',
      'Blanco':   'img/top3.png'
    },
    colors: ['Azul', 'Amarillo', 'Blanco'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'top-bikini',
    name: 'Top Bikini',
    category: 'Tops',
    price: 12,
    description: 'Top estilo bikini con push up integrado.',
    image: 'img/top11.png',
    colorImages: {
      'Rojo':        'img/top11.png',
      'Azul Marino': 'img/top10.png',
      'Vinotinto':   'img/top6.png'
    },
    colors: ['Rojo', 'Azul Marino', 'Vinotinto'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: true
  },
  {
    id: 'top-halter',
    name: 'Top Halter',
    category: 'Tops',
    price: 10,
    description: 'Top halter deportivo de tiras.',
    image: 'img/top7.png',
    colorImages: {
      'Negro':  'img/top7.png',
      'Marrón': 'img/top8.png',
      'Nude':   'img/top9.png'
    },
    colors: ['Negro', 'Marrón', 'Nude'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'top-compresion',
    name: 'Top de Compresión',
    category: 'Tops',
    price: 13,
    description: 'Top de compresión manga larga. Alta elasticidad.',
    image: 'img/top_decompresion.png',
    colorImages: {
      'Blanco':      'img/top_decompresion.png',
      'Azul Marino': 'img/top_mangalarga.png'
    },
    colors: ['Blanco', 'Azul Marino'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: true
  },
  {
    id: 'franela-terry',
    name: 'Franela Terry',
    category: 'Tops',
    price: 6,
    description: 'Franela deportiva en tela terry, señida al cuerpo.',
    image: 'img/franela_terry.png',
    colors: ['Fucsia', 'Rosado', 'Blanco'],
    sizes: ['U'],
    stock: { 'Fucsia-U': 1, 'Rosado-U': 1, 'Blanco-U': 1 },
    featured: false
  },
  {
    id: 'franela-oversize',
    name: 'Franela Oversize',
    category: 'Tops',
    price: 6,
    description: 'Franela deportiva oversize. Talla única.',
    image: 'img/franela_oversize.png',
    colors: ['Beige', 'Verde'],
    sizes: ['U'],
    stock: { 'Beige-U': 2, 'Verde-U': 1 },
    featured: false
  },
  {
    id: 'jacket',
    name: 'Jacket',
    category: 'Tops',
    price: 15,
    description: 'Jacket deportivo de tela delgada.',
    image: 'img/jacket1.png',
    colors: ['Negro', 'Rosado Viejo'],
    sizes: ['M', 'L', 'XL'],
    stock: { 'Negro-M': 1, 'Negro-L': 1, 'Negro-XL': 1, 'Rosado Viejo-M': 1 },
    featured: true
  },
  // ── SUDADERAS ─────────────────────────────────────────────
  {
    id: 'sudadera',
    name: 'Sudadera',
    category: 'Sudaderas',
    price: 12,
    description: 'Sudadera deportiva manga larga.',
    image: 'img/sudadera.png',
    colorImages: {
      'Blanco':      'img/sudadera.png',
      'Blanco Gris': 'img/sudadera2.png',
      'Negro 1':     'img/sudadera3.png',
      'Negro 2':     'img/sudadera4.png'
    },
    colors: ['Blanco', 'Blanco Gris', 'Negro 1', 'Negro 2'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'sudadera-compresion',
    name: 'Sudadera de Compresión',
    category: 'Sudaderas',
    price: 18,
    description: 'Sudadera de compresión manga larga. Caballero.',
    image: 'img/sudadera_decompresion.png',
    colorImages: {
      'Gris':        'img/sudadera_decompresion.png',
      'Azul Marino': 'img/sudadera_decompresion2.png',
      'Blanco':      'img/sudadera_decompresion3.png'
    },
    colors: ['Gris', 'Azul Marino', 'Blanco'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  {
    id: 'sudadera-malla',
    name: 'Sudadera de Malla',
    category: 'Sudaderas',
    price: 6,
    description: 'Sudadera ligera con tejido de malla.',
    image: 'img/sudadera_de_malla.png',
    colorImages: {
      'Negro':  'img/sudadera_de_malla.png',
      'Blanco': 'img/sudadera_de_malla2.png'
    },
    colors: ['Negro', 'Blanco'],
    sizes: ['XS','S','M','L','XL'],
    stock: true,
    featured: false
  },
  // ── SETS / CONJUNTOS ─────────────────────────────────────
  {
    id: 'conjunto',
    name: 'Conjunto',
    category: 'Sets',
    price: 20,
    description: 'Set deportivo completo con efecto push up.',
    image: 'img/conjunto.png',
    colors: ['Rosado', 'Marrón', 'Negro', 'Gris', 'By Color'],
    sizes: ['S/M', 'M', 'L/XL'],
    stock: { 'Rosado-L/XL': 1, 'Marrón-S/M': 1, 'Negro-M': 1, 'Gris-L/XL': 1 },
    featured: true
  },
  {
    id: 'enterizo',
    name: 'Enterizo',
    category: 'Sets',
    price: 20,
    description: 'Enterizo deportivo de una pieza con efecto push up.',
    image: 'img/enterizo.png',
    colors: ['Rojo', 'Rosado', 'Azul Marino', 'Negro'],
    sizes: ['U'],
    stock: { 'Rojo-U': 1, 'Rosado-U': 1, 'Azul Marino-U': 1, 'Negro-U': 1 },
    featured: true
  },
  {
    id: 'mono-deportivo',
    name: 'Mono Deportivo',
    category: 'Leggings',
    price: 18,
    description: 'Mono deportivo unisex de una pieza.',
    image: 'img/mono_deportivo.png',
    colors: ['Negro', 'Rojo', 'Azul Marino', 'Gris', 'Blanco'],
    sizes: ['M', 'U'],
    stock: { 'Negro-M': 1, 'Rojo-U': 1, 'Azul Marino-M': 1, 'Gris-U': 1 },
    featured: true
  },
  // ── CABALLERO ────────────────────────────────────────────
  {
    id: 'short-caballero-1',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero.png',
    colors: ['Vinotinto'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Vinotinto-S': 1, 'Vinotinto-M': 1 },
    featured: true
  },
  {
    id: 'short-caballero-2',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero2.png',
    colors: ['Gris'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Gris-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-3',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero3.png',
    colors: ['Gris Oscuro'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Gris Oscuro-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-4',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero4.png',
    colors: ['Azul'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Azul-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-5',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero5.png',
    colors: ['Beige'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Beige-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-6',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero6.png',
    colors: ['Negro'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-7',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero7.png',
    colors: ['Verde Militar'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Verde Militar-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-8',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero8.png',
    colors: ['Blanco'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Blanco-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-9',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero9.png',
    colors: ['Azul Marino'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Azul Marino-M': 1 },
    featured: false
  },
  {
    id: 'short-caballero-10',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero10.png',
    colors: ['Negro'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Negro-L': 1 },
    featured: false
  },
  {
    id: 'short-caballero-11',
    name: 'Short Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Short deportivo para caballero.',
    image: 'img/short_caballero11.png',
    colors: ['Verde Oliva'],
    sizes: ['S', 'M', 'L'],
    stock: { 'Verde Oliva-M': 1 },
    featured: false
  },
  {
    id: 'franelilla-1',
    name: 'Franelilla',
    category: 'Caballero',
    price: 14,
    description: 'Franelilla deportiva sin mangas para caballero.',
    image: 'img/franelilla.png',
    colors: ['Gris'],
    sizes: ['M'],
    stock: { 'Gris-M': 1 },
    featured: false
  },
  {
    id: 'franelilla-2',
    name: 'Franelilla',
    category: 'Caballero',
    price: 14,
    description: 'Franelilla deportiva sin mangas para caballero.',
    image: 'img/franelilla2.png',
    colors: ['Negro'],
    sizes: ['M'],
    stock: { 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'franelilla-3',
    name: 'Franelilla',
    category: 'Caballero',
    price: 14,
    description: 'Franelilla deportiva sin mangas para caballero.',
    image: 'img/franelilla3.png',
    colors: ['Negro 2'],
    sizes: ['M'],
    stock: { 'Negro 2-M': 1 },
    featured: false
  },
  {
    id: 'franelilla-4',
    name: 'Franelilla',
    category: 'Caballero',
    price: 14,
    description: 'Franelilla deportiva sin mangas para caballero.',
    image: 'img/franelilla4.png',
    colors: ['Blanco'],
    sizes: ['M'],
    stock: { 'Blanco-M': 1 },
    featured: false
  },
  {
    id: 'franela-caballero-1',
    name: 'Franela Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Franela deportiva para caballero.',
    image: 'img/franela2.png',
    colors: ['Blanco'],
    sizes: ['XL'],
    stock: { 'Blanco-XL': 1 },
    featured: false
  },
  {
    id: 'franela-caballero-2',
    name: 'Franela Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Franela deportiva para caballero.',
    image: 'img/franela3.png',
    colors: ['Blanco 2'],
    sizes: ['XL'],
    stock: { 'Blanco 2-XL': 1 },
    featured: false
  },
  {
    id: 'franela-caballero-3',
    name: 'Franela Caballero',
    category: 'Caballero',
    price: 10,
    description: 'Franela deportiva para caballero.',
    image: 'img/franela4.png',
    colors: ['Negro'],
    sizes: ['M'],
    stock: { 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'franela-compresion-1',
    name: 'Franela de Compresión',
    category: 'Caballero',
    price: 14,
    description: 'Franela de compresión manga larga para caballero.',
    image: 'img/franela_decompresion.png',
    colors: ['Blanco'],
    sizes: ['U'],
    stock: { 'Blanco-U': 1 },
    featured: false
  },
  {
    id: 'franela-compresion-2',
    name: 'Franela de Compresión',
    category: 'Caballero',
    price: 14,
    description: 'Franela de compresión manga larga para caballero.',
    image: 'img/franela_decompresion2.png',
    colors: ['Negro'],
    sizes: ['U'],
    stock: { 'Negro-U': 1 },
    featured: false
  },
  {
    id: 'franela-compresion-3',
    name: 'Franela de Compresión',
    category: 'Caballero',
    price: 14,
    description: 'Franela de compresión manga larga para caballero.',
    image: 'img/franela_decompresion3.png',
    colors: ['Negro 2'],
    sizes: ['U'],
    stock: { 'Negro 2-U': 1 },
    featured: false
  },
  {
    id: 'franela-compresion-4',
    name: 'Franela de Compresión',
    category: 'Caballero',
    price: 14,
    description: 'Franela de compresión manga larga para caballero.',
    image: 'img/franela_decompresion4.png',
    colors: ['Rojo'],
    sizes: ['U'],
    stock: { 'Rojo-U': 1 },
    featured: false
  },
  {
    id: 'franela-compresion-5',
    name: 'Franela de Compresión',
    category: 'Caballero',
    price: 14,
    description: 'Franela de compresión manga larga para caballero.',
    image: 'img/franela_decompresion5.png',
    colors: ['Blanco 2'],
    sizes: ['U'],
    stock: { 'Blanco 2-U': 1 },
    featured: false
  },
  {
    id: 'sudadera-compresion-1',
    name: 'Sudadera de Compresión',
    category: 'Caballero',
    price: 18,
    description: 'Sudadera de compresión manga larga.',
    image: 'img/sudadera_decompresion.png',
    colors: ['Blanco'],
    sizes: ['S'],
    stock: { 'Blanco-S': 1 },
    featured: false
  },
  {
    id: 'sudadera-compresion-2',
    name: 'Sudadera de Compresión',
    category: 'Caballero',
    price: 18,
    description: 'Sudadera de compresión manga larga.',
    image: 'img/sudadera_decompresion2.png',
    colors: ['Azul Marino'],
    sizes: ['L'],
    stock: { 'Azul Marino-L': 1 },
    featured: false
  },
  {
    id: 'sudadera-compresion-3',
    name: 'Sudadera de Compresión',
    category: 'Caballero',
    price: 18,
    description: 'Sudadera de compresión manga larga.',
    image: 'img/sudadera_decompresion3.png',
    colors: ['Gris'],
    sizes: ['M'],
    stock: { 'Gris-M': 1 },
    featured: false
  },
  {
    id: 'sudadera-1',
    name: 'Sudadera',
    category: 'Caballero',
    price: 12,
    description: 'Sudadera deportiva para caballero.',
    image: 'img/sudadera.png',
    colors: ['Blanco'],
    sizes: ['L'],
    stock: { 'Blanco-L': 1 },
    featured: false
  },
  {
    id: 'sudadera-2',
    name: 'Sudadera',
    category: 'Caballero',
    price: 12,
    description: 'Sudadera deportiva para caballero.',
    image: 'img/sudadera2.png',
    colors: ['Blanco 2'],
    sizes: ['M'],
    stock: { 'Blanco 2-M': 1 },
    featured: false
  },
  {
    id: 'sudadera-3',
    name: 'Sudadera',
    category: 'Caballero',
    price: 12,
    description: 'Sudadera deportiva para caballero.',
    image: 'img/sudadera3.png',
    colors: ['Negro'],
    sizes: ['M'],
    stock: { 'Negro-M': 1 },
    featured: false
  },
  {
    id: 'sudadera-4',
    name: 'Sudadera',
    category: 'Caballero',
    price: 12,
    description: 'Sudadera deportiva para caballero.',
    image: 'img/sudadera4.png',
    colors: ['By Color'],
    sizes: ['M'],
    stock: { 'By Color-M': 1 },
    featured: false
  },
  // ── ACCESORIOS ───────────────────────────────────────────
  {
    id: 'colas',
    name: 'Colitas (x5)',
    category: 'Accesorios',
    price: 0.70,
    description: 'Paquete de 5 colas para el cabello.',
    image: 'img/colitas.png',
    colors: ['Negro', 'By Color'],
    sizes: ['U'],
    stock: { 'Negro-U': 20, 'By Color-U': 20 },
    featured: false
  },
  {
    id: 'colas-seda',
    name: 'Colitas de Satín (x2)',
    category: 'Accesorios',
    price: 1.20,
    description: 'Paquete de 2 colas de satín suaves.',
    image: 'img/colitas_satin.png',
    colors: ['By Color'],
    sizes: ['U'],
    stock: { 'By Color-U': 5 },
    featured: false
  },
  {
    id: 'lentes',
    name: 'Lentes Deportivos',
    category: 'Accesorios',
    price: 10,
    description: 'Lentes deportivos con protección UV.',
    image: 'img/lentes.png',
    colors: ['Negro', 'By Color'],
    sizes: ['U'],
    stock: { 'Negro-U': 2, 'By Color-U': 1 },
    featured: false
  },
  {
    id: 'bandas-resistencia',
    name: 'Bandas de Resistencia',
    category: 'Accesorios',
    price: 12,
    description: 'Set de bandas de resistencia progresiva.',
    image: 'img/banditas.png',
    colors: ['By Color'],
    sizes: ['U'],
    stock: { 'By Color-U': 3 },
    featured: false
  },
  {
    id: 'morral',
    name: 'Morral',
    category: 'Accesorios',
    price: 8,
    description: 'Morral deportivo resistente.',
    image: 'img/placeholder.jpg',
    colors: ['Negro', 'Rojo', 'Azul', 'Verde', 'By Color'],
    sizes: ['U'],
    stock: { 'Negro-U': 2, 'Rojo-U': 1, 'Azul-U': 1 },
    featured: false
  },
  {
    id: 'bolso-cintura',
    name: 'Bolso de Cintura',
    category: 'Accesorios',
    price: 10,
    description: 'Bolso de cintura ligero para entrenamiento.',
    image: 'img/placeholder.jpg',
    colors: ['Negro'],
    sizes: ['U'],
    stock: { 'Negro-U': 1 },
    featured: false
  }
];

if (typeof module !== 'undefined') module.exports = { PRODUCTS };
